### ISSUE TITLE
Heat demand intraday profile

### ISSUE THREAD

**Issue by MichelJD** [PyPSA/pypsa-eur-sec#159]
Hello pypsa-(eur-sec-)team!

First of all: thanks a lot for your great work and effort you put into the project.
I am currently writing my masters thesis using your pypsa-eur-sec model and I got some pretty nice results and am really happy!

I think I encountered a mistake you made, when building the heat demand profiles in the  prepare_sector_network.py file. The intraday profiles state, that there is a profile in the space heat demand and a constant demand in the hot water fraction. It should be the other way around. 

Now there are some time periods with constant heat demand in the summertime, when there is no space heat needed (see attached screenshot).
![Screenshot 2021-08-18 164051](https://user-images.githubusercontent.com/79583494/129918750-2731cdfa-0088-4f0a-a2a7-c89048698b43.png)
 
The other way around there are some big variations in the wintertime (see screenshot), when there should only be small variations as the space heat demand is high, dominant and almost constant
![Screenshot 2021-08-18 164516](https://user-images.githubusercontent.com/79583494/129920877-58030aef-a718-4b0e-acca-00ba60897237.png)

The mistake results in higher peak heat demand, so it can have quite an influence in heat generator capacity and corresponding investement costs. 
So just wanted to let you know ;)

Best wishes and keep up the great work!
Michél

**Comment by lisazeyen** [comment]
@energyLS has a look

**Comment by energyLS** [comment]
Hey Michél,

sorry for the late reply. We are pleased to hear of you using PyPSA-Eur-Sec in your master's thesis.

The intraday heat demand profiles are derived from BDEW (see https://demandlib.readthedocs.io/en/latest/bdew.html) and stored in `data/heat_load_profile_BDEW.csv`, which vary by sector (residential or service) and by weekday (working day or weekend). The intraday heat profile is in fact highly variable reflecting the typical end-user behaviour, since the heating units are required to supply space heating during the morning hours (to heat up the buildings after night-time reductions of heating temperatures) and in the evening (people returning back to their homes).
The daily space heating demand depends on the ambient temperature, assuming that the heating demand rises linearly below an average daily temperature of 15°C.

The hot water demand profile is constant during the year. That could be implemented in higher detail (see https://doi.org/10.1016/j.rser.2017.05.229) but has less influence on the results compared to the heating demand.

Given this insight, it makes sense that during summer the combined heating demand is constant at certain periods. It's true, in winter the space heating demand is high and dominant, but following the BDEW profile it is not constant but rather variable within a 24h-cycle.

Best,

Leon

**Comment by MichelJD** [comment]
Hi Leon @energyLS 

thanks for your detailed reply.

Okay, I see. Assuming the hot water demand as constant is definitely valid for the winter time, as it's not the dominant source of heat demand. And the daily demand peaks in summer time are not really relevant for economic optimization.

Still, the profiles vary too much in the wintertime. I think that has two main reasons:

1. The night time reduction is NOT a typically end user behaviour. There might be buildings, where it is the case, but in most buildings there is no such control implemented and most consumers don't turn down their radiators during the night. So also in real operation data the effect of night time reduction that can be seen, is also much smaller than it is assumed in the BDEW profiles. Also, as buildings get better insulation, night time reduction becomes more irrelevant, as they behave very slow.
2. The BDEW profiles are supposed to model single houses and not large district heating systems. In district heating systems you will have utilisation factors, as not all consumers need the demand at the same time. In district heating systems they are somewhat between 0,65 and 0,8.

Taking both reasons into account, the demand profile that has to be supplied by a heat generator/storage would be smoother (lower influence of night time reduction) and the peaks would be smaller (general utilisation factor).

By the way, my masters thesis was a great success, also thanks to your work here. I had a lot of fun using your pips-eur-sec and learned a lot during that time.

Best wishes,
Michél

**Comment by MichelJD** [comment]
Hi Leon @energyLS 

You can have a look at some real time data. The load of a big city during a cold period of 4 days.
Difference between minimum to maximum load is more in the range of +30% instead of +100%.

![Capture](https://user-images.githubusercontent.com/79583494/179171434-86fabe09-7fbe-4dab-a839-9b14b6e6b988.PNG)


Have a good weekend
Michél

**Comment by energyLS** [comment]
Hi @MichelJD,

I totally agree with your two points, also backed by the data you mentioned. Do you have any dataset (European scale, if possible) which we could incorporate? Or any idea how to improve our methodology?
If we find some way how to include it, we are happy to take this forward!

Best,
Leon
